export type SieveAlgorithmId = 'eratosthenes' | 'linear' | 'sundaram' | 'lucky';

export type SieveAlgorithmMeta = {
  id: SieveAlgorithmId;
  name: string;
  shortName: string;
  description: string;
  complexity: string;
  resultLabel: string;
  bestFor: string;
  pseudocode: string[];
};

export type SieveFrame = {
  phase: string;
  title: string;
  detail: string;
  formula?: string;
  active: number[];
  touched: number[];
  eliminated: boolean[];
  results: boolean[];
  owner: number[];
  inspections: number;
  writes: number;
  revisits: number;
};

export type SieveRun = {
  algorithm: SieveAlgorithmId;
  limit: number;
  frames: SieveFrame[];
  values: number[];
  resultLabel: string;
};

export const SIEVE_ALGORITHMS: SieveAlgorithmMeta[] = [
  {
    id: 'eratosthenes',
    name: 'Sieve of Eratosthenes',
    shortName: 'Eratosthenes',
    description: 'Repeatedly choose the next surviving prime and cross out its multiples, beginning at p².',
    complexity: 'O(n log log n)',
    resultLabel: 'primes',
    bestFor: 'The clearest visual explanation of prime sieving.',
    pseudocode: [
      'mark 0 and 1 as non-prime',
      'for p from 2 while p² ≤ n',
      '  if p is still a candidate',
      '    cross out p², p²+p, …',
      'the remaining values are prime',
    ],
  },
  {
    id: 'linear',
    name: "Euler's Linear Sieve",
    shortName: 'Euler linear',
    description: 'Assign every composite exactly once, using its smallest prime factor as its owner.',
    complexity: 'O(n)',
    resultLabel: 'primes',
    bestFor: 'Seeing why a linear sieve avoids duplicate composite writes.',
    pseudocode: [
      'keep a list of discovered primes',
      'for each i from 2 to n',
      '  if i has no least prime factor, i is prime',
      '  for primes p ≤ leastPrime[i]',
      '    set leastPrime[i × p] = p',
    ],
  },
  {
    id: 'sundaram',
    name: 'Sieve of Sundaram',
    shortName: 'Sundaram',
    description: 'Remove odd-number indexes generated by i + j + 2ij, then map the survivors through 2k + 1.',
    complexity: 'O(n log n)',
    resultLabel: 'primes',
    bestFor: 'A visually distinctive algebraic route to odd primes.',
    pseudocode: [
      'start with indexes 1 … ⌊(n−1)/2⌋',
      'remove k = i + j + 2ij',
      'map every surviving k to 2k + 1',
      'include 2 separately',
    ],
  },
  {
    id: 'lucky',
    name: 'Lucky Number Sieve',
    shortName: 'Lucky numbers',
    description: 'Delete values according to their changing positions among survivors instead of divisibility.',
    complexity: 'Position-based iterative sieve',
    resultLabel: 'lucky numbers',
    bestFor: 'Watching a self-referential sequence emerge from repeated survivor counts.',
    pseudocode: [
      'begin with 1, 2, 3, 4, …',
      'remove every second surviving value',
      'the next survivor is the new step size',
      'remove every step-th survivor',
      'repeat while the step fits the list',
    ],
  },
];

export const MIN_SIEVE_LIMIT = 10;
export const MAX_SIEVE_LIMIT = 240;

export function clampSieveLimit(value: number): number {
  if (!Number.isFinite(value)) return MIN_SIEVE_LIMIT;
  return Math.min(MAX_SIEVE_LIMIT, Math.max(MIN_SIEVE_LIMIT, Math.floor(value)));
}

type RecorderState = {
  limit: number;
  eliminated: boolean[];
  results: boolean[];
  owner: number[];
  inspections: number;
  writes: number;
  revisits: number;
  frames: SieveFrame[];
};

function createRecorder(limit: number, eliminateOne = true): RecorderState {
  const eliminated = Array<boolean>(limit + 1).fill(false);
  eliminated[0] = true;
  if (eliminateOne && limit >= 1) eliminated[1] = true;
  return {
    limit,
    eliminated,
    results: Array<boolean>(limit + 1).fill(false),
    owner: Array<number>(limit + 1).fill(0),
    inspections: 0,
    writes: 0,
    revisits: 0,
    frames: [],
  };
}

function recordFrame(
  state: RecorderState,
  frame: Omit<SieveFrame, 'eliminated' | 'results' | 'owner' | 'inspections' | 'writes' | 'revisits'>,
): void {
  state.frames.push({
    ...frame,
    eliminated: [...state.eliminated],
    results: [...state.results],
    owner: [...state.owner],
    inspections: state.inspections,
    writes: state.writes,
    revisits: state.revisits,
  });
}

function finishRun(
  algorithm: SieveAlgorithmId,
  state: RecorderState,
  values: number[],
  resultLabel: string,
  detail: string,
): SieveRun {
  state.results.fill(false);
  for (const value of values) state.results[value] = true;
  recordFrame(state, {
    phase: 'Complete',
    title: `${values.length} ${resultLabel} remain`,
    detail,
    active: [],
    touched: [],
  });
  return { algorithm, limit: state.limit, frames: state.frames, values, resultLabel };
}

function runEratosthenes(limit: number): SieveRun {
  const state = createRecorder(limit);
  recordFrame(state, {
    phase: 'Prepare',
    title: 'Prepare the candidate field',
    detail: `Every integer from 2 through ${limit} begins as a possible prime.`,
    active: [],
    touched: [],
  });

  for (let p = 2; p * p <= limit; p += 1) {
    state.inspections += 1;
    if (state.eliminated[p]) {
      state.revisits += 1;
      recordFrame(state, {
        phase: 'Choose base',
        title: `${p} is already known to be composite`,
        detail: 'Only surviving bases generate a new crossing-out pass.',
        active: [p],
        touched: [p],
      });
      continue;
    }

    recordFrame(state, {
      phase: 'Choose base',
      title: `Use ${p} as the next prime base`,
      detail: `Multiples below ${p}² were already handled by smaller primes.`,
      formula: `${p}² = ${p * p}`,
      active: [p],
      touched: [],
    });

    for (let multiple = p * p; multiple <= limit; multiple += p) {
      state.inspections += 1;
      const wasEliminated = state.eliminated[multiple];
      if (wasEliminated) {
        state.revisits += 1;
      } else {
        state.eliminated[multiple] = true;
        state.owner[multiple] = p;
        state.writes += 1;
      }
      recordFrame(state, {
        phase: 'Cross out multiples',
        title: wasEliminated ? `${multiple} was already crossed out` : `Cross out ${multiple}`,
        detail: wasEliminated
          ? `${multiple} has more than one prime factor, so this pass touches it again.`
          : `${multiple} is divisible by ${p}.`,
        formula: `${p} × ${multiple / p} = ${multiple}`,
        active: [p],
        touched: [multiple],
      });
    }
  }

  const values = Array.from({ length: limit - 1 }, (_, index) => index + 2).filter((value) => !state.eliminated[value]);
  return finishRun('eratosthenes', state, values, 'primes', 'Every surviving candidate has no divisor at or below its square root.');
}

function runLinear(limit: number): SieveRun {
  const state = createRecorder(limit);
  const leastPrime = Array<number>(limit + 1).fill(0);
  const primes: number[] = [];

  recordFrame(state, {
    phase: 'Prepare',
    title: 'Prepare least-prime-factor slots',
    detail: 'A zero slot means the value has not yet been generated as a composite.',
    active: [],
    touched: [],
  });

  for (let value = 2; value <= limit; value += 1) {
    state.inspections += 1;
    if (leastPrime[value] === 0) {
      leastPrime[value] = value;
      primes.push(value);
      recordFrame(state, {
        phase: 'Discover prime',
        title: `${value} is prime`,
        detail: 'No earlier prime generated this value as a composite.',
        active: [value],
        touched: [value],
      });
    } else {
      recordFrame(state, {
        phase: 'Advance',
        title: `Advance through composite ${value}`,
        detail: `Its smallest prime factor is ${leastPrime[value]}.`,
        formula: `spf(${value}) = ${leastPrime[value]}`,
        active: [value],
        touched: [value],
      });
    }

    for (const prime of primes) {
      const composite = value * prime;
      if (composite > limit || prime > leastPrime[value]) break;
      state.inspections += 1;
      if (leastPrime[composite] !== 0) {
        state.revisits += 1;
      } else {
        leastPrime[composite] = prime;
        state.eliminated[composite] = true;
        state.owner[composite] = prime;
        state.writes += 1;
      }
      recordFrame(state, {
        phase: 'Assign composite',
        title: `Assign ${composite} to ${prime}`,
        detail: `${prime} is the smallest prime factor of ${composite}; this composite will not be assigned again.`,
        formula: `${value} × ${prime} = ${composite}`,
        active: [value, prime],
        touched: [composite],
      });
    }
  }

  return finishRun('linear', state, primes, 'primes', 'Each composite was written once by its smallest prime factor.');
}

function runSundaram(limit: number): SieveRun {
  const state = createRecorder(limit);
  const evenValues: number[] = [];
  for (let value = 4; value <= limit; value += 2) {
    state.eliminated[value] = true;
    state.owner[value] = 2;
    state.writes += 1;
    evenValues.push(value);
  }

  recordFrame(state, {
    phase: 'Prepare odd candidates',
    title: 'Set aside 2 and remove larger evens',
    detail: 'Sundaram works on indexes that later map to odd values through 2k + 1.',
    formula: 'odd value = 2k + 1',
    active: [2],
    touched: evenValues,
  });

  const indexLimit = Math.floor((limit - 1) / 2);
  for (let i = 1; i <= indexLimit; i += 1) {
    for (let j = i; ; j += 1) {
      const index = i + j + 2 * i * j;
      if (index > indexLimit) break;
      const value = 2 * index + 1;
      state.inspections += 1;
      const wasEliminated = state.eliminated[value];
      if (wasEliminated) {
        state.revisits += 1;
      } else {
        state.eliminated[value] = true;
        state.owner[value] = 2 * i + 1;
        state.writes += 1;
      }
      recordFrame(state, {
        phase: 'Apply quadratic form',
        title: wasEliminated ? `${value} was already removed` : `Remove ${value}`,
        detail: `The index ${index} is generated by i=${i} and j=${j}, so 2×${index}+1 cannot be prime.`,
        formula: `k = ${i} + ${j} + 2·${i}·${j} = ${index}`,
        active: [2 * i + 1, 2 * j + 1].filter((candidate) => candidate <= limit),
        touched: [value],
      });
    }
  }

  const values = [2, ...Array.from({ length: indexLimit }, (_, index) => 2 * (index + 1) + 1)]
    .filter((value) => value <= limit && !state.eliminated[value]);
  return finishRun('sundaram', state, values, 'primes', 'The surviving indexes map exactly to the odd primes, with 2 added separately.');
}

function runLucky(limit: number): SieveRun {
  const state = createRecorder(limit, false);
  const initial = Array.from({ length: limit }, (_, index) => index + 1);
  let survivors = [...initial];

  recordFrame(state, {
    phase: 'Prepare',
    title: 'Begin with every positive integer',
    detail: 'Lucky numbers are determined by positions in the changing survivor list, not by factors.',
    active: [],
    touched: [],
  });

  const applyPass = (step: number, label: string): void => {
    state.inspections += survivors.length;
    recordFrame(state, {
      phase: 'Choose step',
      title: label,
      detail: `Count through the ${survivors.length} current survivors and remove every ${step}${ordinalSuffix(step)} position.`,
      formula: `step size = ${step}`,
      active: [step],
      touched: [],
    });

    const removed = survivors.filter((_, index) => (index + 1) % step === 0);
    for (const value of removed) {
      state.eliminated[value] = true;
      state.owner[value] = step;
      state.writes += 1;
      recordFrame(state, {
        phase: 'Remove by position',
        title: `Remove ${value}`,
        detail: `${value} occupies a multiple-of-${step} position in the current survivor list.`,
        active: [step],
        touched: [value],
      });
    }
    const removedSet = new Set(removed);
    survivors = survivors.filter((value) => !removedSet.has(value));
  };

  applyPass(2, 'First pass: remove every second value');
  let survivorIndex = 1;
  while (survivorIndex < survivors.length) {
    const step = survivors[survivorIndex];
    if (step > survivors.length) break;
    applyPass(step, `${step} becomes the next lucky step`);
    survivorIndex += 1;
  }

  return finishRun('lucky', state, survivors, 'lucky numbers', 'The remaining values survived every position-based elimination pass.');
}

function ordinalSuffix(value: number): string {
  const mod100 = value % 100;
  if (mod100 >= 11 && mod100 <= 13) return 'th';
  switch (value % 10) {
    case 1: return 'st';
    case 2: return 'nd';
    case 3: return 'rd';
    default: return 'th';
  }
}

export function runSieveAlgorithm(algorithm: SieveAlgorithmId, requestedLimit: number): SieveRun {
  const limit = clampSieveLimit(requestedLimit);
  switch (algorithm) {
    case 'linear': return runLinear(limit);
    case 'sundaram': return runSundaram(limit);
    case 'lucky': return runLucky(limit);
    case 'eratosthenes':
    default: return runEratosthenes(limit);
  }
}
